### ISSUE TITLE
A question about the unsupervised learning of video representations using LSTMs

### ISSUE THREAD

**Issue by LeZhengThu** [springzfx/FDOG#1]
Hi, I'm a PhD student from Beijing and I read your comment on the github project 'unsupervised learning of video representations using LSTMs'. I have several questions about it but the original author did not respond to me. So I leave a message here and try to seek help. Thanks in advance. My email address is zhengl07@mails.tsinghua.edu.cn, and my wechat is 825698341. Please contact and help me.

**Comment by springzfx** [comment]
Sorry, can you give the link to these questions you ask?

**Comment by LeZhengThu** [comment]
@springzfx Hi, thank you for the reply. The link is https://github.com/emansim/unsupervised-videos
1. I don't understand how the author prepare the data for the classification task. What does the file xxx_num_frames.txt mean? As far as I can understand, I think the x.npy data contains all the frame data 17701_4096, then the author need to get 100_16*4096 (since there are only 100 labels and seq_length=16) data from the file. But it seems it is not the case so that I'm confused.
2. It seems that the classify example provided by the author doesn't contain the encoder-decoder pre-training process that he claimed. Am I right? I want to add the encoder-decoder blocks to see if it can fit my case, but I just don't know how to revise the code.

Thank you very much. Are you Chinese? If I did not make myself clear, maybe we can use Chinese to communicate in the email.
